'blank_issues_enabled': true
'contact_links':
  - 'about': >
        Please report filtering issues, for example advertising filters
        misfiring or safe browsing false positives, using the form on our
        website
    'name': 'AdGuard filters issues'
    'url': 'https://link.adtidy.org/forward.html?action=report&app=home&from=github'
  - 'about': >
        Please send requests for new blocked services and vetted filtering lists
        to the Hostlists Registry repository
    'name': 'Blocked services and vetted filtering rule lists: AdGuard Hostlists Registry'
    'url': 'https://github.com/AdguardTeam/HostlistsRegistry'