//go:build generate

package main

import (
	"cmp"
	"context"
	"encoding/csv"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"os"
	"slices"
	"strconv"
	"strings"
	"text/template"
	"time"
	"unicode/utf8"

	"github.com/AdguardTeam/AdGuardDNS/internal/agdhttp"
	"github.com/AdguardTeam/golibs/errors"
	"github.com/AdguardTeam/golibs/httphdr"
	"github.com/AdguardTeam/golibs/logutil/slogutil"
	"github.com/AdguardTeam/golibs/osutil"
)

// defaultTimeout is the default timeout for the HTTP client.
const defaultTimeout = 10 * time.Second

// defaultConfusablesURL is the default URL to get the confusables.txt file.
//
// TODO(e.burkov):  Update to 16.0.0 when the [unicode] package will use it.
const defaultConfusablesURL = `https://www.unicode.org/Public/security/15.0.0/confusables.txt`

func main() {
	ctx := context.Background()
	logger := slogutil.New(nil)
	defer slogutil.RecoverAndExit(ctx, logger, osutil.ExitCodeFailure)

	confusablesURL := defaultConfusablesURL
	if u, ok := os.LookupEnv("CONFUSABLES_URL"); ok {
		confusablesURL = u
	}

	c := &http.Client{
		Timeout: defaultTimeout,
	}

	req := errors.Must(http.NewRequestWithContext(ctx, http.MethodGet, confusablesURL, nil))

	req.Header.Add(httphdr.UserAgent, agdhttp.UserAgent())

	resp := errors.Must(c.Do(req))
	defer slogutil.CloseAndLog(ctx, logger, resp.Body, slog.LevelError)

	errors.Check(agdhttp.CheckStatus(resp, http.StatusOK))

	out := errors.Must(os.OpenFile("./confusables.go", os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0o664))
	defer slogutil.CloseAndLog(ctx, logger, out, slog.LevelError)

	reader := csv.NewReader(resp.Body)
	reader.Comma = ';'
	reader.Comment = '#'
	reader.FieldsPerRecord = -1
	reader.ReuseRecord = true
	reader.LazyQuotes = true

	type templateData struct {
		CodePoint int64
		Prototype string
	}

	var data []templateData
	var buf []byte

	for recs, err := reader.Read(); err != io.EOF; recs, err = reader.Read() {
		errors.Check(errors.Annotate(err, "line: %q; %w", recs))

		td := templateData{}

		td.CodePoint, err = strconv.ParseInt(strings.TrimSpace(recs[0]), 16, 32)
		errors.Check(errors.Annotate(err, "code point: %q: %w", recs[0]))

		buf = buf[:0]

		for cp := range strings.SplitSeq(strings.TrimSpace(recs[1]), " ") {
			r, err := strconv.ParseInt(cp, 16, 32)
			errors.Check(errors.Annotate(err, "code points: %q: %w", recs[1]))

			buf = utf8.AppendRune(buf, rune(r))
		}

		td.Prototype = strings.TrimPrefix(fmt.Sprintf("%#v", buf), "[]byte")

		data = append(data, td)
	}

	slices.SortStableFunc(data, func(x, y templateData) (res int) {
		return cmp.Compare(x.CodePoint, y.CodePoint)
	})

	tmpl := template.Must(template.New("main").Parse(tmplStr))
	errors.Check(tmpl.Execute(out, data))
}

// tmplStr is the template of the generated Go code.
const tmplStr = `// Code generated by go run ./confusables_generate.go; DO NOT EDIT.

package agdalg

// confusables is an array of confusable code points prototypes indexed by the
// code point.  The array is used instead of map as it gives better performance
// and the memory overhead is acceptable.
//
// TODO(e.burkov):  Consider using a more appropriate data structure to
// eliminate the memory overhead of the array.
var confusables = [...][]byte{
{{- range $data := . }}
	{{ $data.CodePoint }}: {{ $data.Prototype }},
{{- end }}
}

// confusablePrototyper replaces each rune with its confusable prototype.  If a
// rune has no confusable prototype, it is passed as is.
var confusablePrototyper = &runePrototyper{
	prototypes: confusables[:],
}
`
